# SPDX-License-Identifier: CC0-1.0

# This file contains configuration for this repository on GitHub [https://github.com/openmirrors/xkcd].

---

branches:
- name: 'main'
  enforce_admins: null
  required_status_checks: null
  required_linear_history: true
  restrictions: null
  protection:
    required_pull_request_reviews:
      dismiss_stale_reviews: false
      required_approving_review_count: 1
      require_code_owner_reviews: false

labels: null

milestones: null

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  default_branch: 'main'
  delete_branch_on_merge: false
  description: 'a mirror of the webcomic xkcd, including comics, title text, transcripts, JSON, etc. Itâ€™s all manual, so contributions are very welcome and appreciated!'
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false
  has_downloads: true
  has_issues:    true
  has_projects:  false
  has_wiki:      false
  homepage: 'https://xkcd.com/'
  name: 'xkcd'
  private: false
  topics: 'comic,mirror,webcomic,xkcd'

teams: null

...
