# SPDX-License-Identifier: CC0-1.0

# This file contains configuration for this repository on GitHub [https://github.com/openmirrors/xkcd/].

---

repository:
  name: xkcd
  description: a mirror of the webcomic xkcd, including comics, title text, transcripts, JSON, etc. It's all manual, so contributions are very welcome and appreciated!
  homepage: https://xkcd.com/
  topics:   comic,mirror,webcomic,xkcd
  private: false
  has_issues:    true
  has_downloads: true
  has_projects:  false
  has_wiki:      false
  default_branch: main
  allow_merge_commit: true
  allow_squash_merge: false
  allow_rebase_merge: false
  delete_branch_on_merge:          false
  enable_automated_security_fixes: false
  enable_vulnerability_alerts:     false

branches:
- name: main
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      require_code_owner_reviews: true
      dismiss_stale_reviews:      false
  enforce_admins:         null
  required_status_checks: null
  restrictions:           null
  required_linear_history: true

collaborators:
- username: gabldotink

labels:     null
milestones: null
teams:      null

...
